<a href="https://colab.research.google.com/github/trungnguyendang/GaussianNB_classifier/blob/main/Untitled17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Load the Census Income dataset
adult_data = pd.read_csv("/content/drive/MyDrive/Census_dataset/data.csv")
adult_data.head(9)

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K

In [ ]:
# prompt: show number of rows in the adult_data

print(len(adult_data))

32561

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Convert categorical variables to numerical values
le = LabelEncoder()
categorical_features = ['Workclass', 'Education', 'Marital Status',
                        'Occupation', 'Relationship', 'Race', 'Gender',
                        'Native Country', 'Income']
for feature in categorical_features:
    adult_data[feature] = le.fit_transform(adult_data[feature])

# Normalize continuous variables
adult_data[
  ['Age', 'Final Weight', 'EducationNum', 'Capital Gain',
             'capital loss', 'Hours per Week']] = adult_data[
['Age', 'Final Weight', 'EducationNum', 'Capital Gain',
             'capital loss', 'Hours per Week']].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

# Display the preprocessed data
adult_data.head()

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,0.301370,7,0.044302,9,0.800000,4,1,1,4,1,0.02174,0.0,0.397959,39,0
1,0.452055,6,0.048238,9,0.800000,2,4,0,4,1,0.00000,0.0,0.122449,39,0
2,0.287671,4,0.138113,11,0.533333,0,6,1,4,1,0.00000,0.0,0.397959,39,0
3,0.493151,4,0.151068,1,0.400000,2,6,0,2,1,0.00000,0.0,0.397959,39,0
4,0.150685,4,0.221488,9,0.800000,2,10,5,2,0,0.00000,0.0,0.397959,5,0

In [ ]:


# Extract features and labels
X = adult_data.drop('Income', axis=1)
y = adult_data['Income']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Train the model
gnb.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = gnb.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.8086805200122837

In [ ]:
predictions_df = X_test.copy()
predictions_df['Actual Income'] = y_test.values
predictions_df['Predicted Income'] = y_pred

#extract the output file
predictions_df.to_csv("/content/drive/MyDrive/Census_dataset/predicted_income.csv", index=False)

GaussianNB Custom Code

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from scipy.stats import norm
import math
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Load the Census Income dataset
adult_data_1 = pd.read_csv("/content/drive/MyDrive/Census_dataset/adult.csv")
adult_data_1.head(5)

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:

# Convert categorical variables to numerical values
le = LabelEncoder()
categorical_features = ['Workclass', 'Education', 'Marital Status',
                        'Occupation', 'Relationship', 'Race', 'Gender',
                        'Native Country', 'Income']
for feature in categorical_features:
    adult_data_1[feature] = le.fit_transform(adult_data_1[feature])

# Normalize continuous variables
adult_data_1[
  ['Age', 'Final Weight', 'EducationNum', 'Capital Gain',
             'capital loss', 'Hours per Week']] = adult_data_1[
['Age', 'Final Weight', 'EducationNum', 'Capital Gain',
             'capital loss', 'Hours per Week']].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

# Display the preprocessed data
adult_data_1.head()

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,0.301370,7,0.044302,9,0.800000,4,1,1,4,1,0.02174,0.0,0.397959,39,0
1,0.452055,6,0.048238,9,0.800000,2,4,0,4,1,0.00000,0.0,0.122449,39,0
2,0.287671,4,0.138113,11,0.533333,0,6,1,4,1,0.00000,0.0,0.397959,39,0
3,0.493151,4,0.151068,1,0.400000,2,6,0,2,1,0.00000,0.0,0.397959,39,0
4,0.150685,4,0.221488,9,0.800000,2,10,5,2,0,0.00000,0.0,0.397959,5,0

In [ ]:

# Extract features and labels
X = adult_data.drop('Income', axis=1)
y = adult_data['Income']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

def gaussian_pdf(x, mean, std):
    """ Tính xác suất theo phân phối chuẩn (Gaussian PDF) """
    variance = std ** 2
    coeff = 1 / math.sqrt(2 * math.pi * variance)
    exponent = math.exp(-((x - mean) ** 2) / (2 * variance))
    return coeff * exponent


def train_gaussian_nb(X_train, y_train):
    """ Huấn luyện mô hình Gaussian Naive Bayes """
    classes = y_train.unique()
    model = {}

    for cls in classes:
        X_class = X_train[y_train == cls]
        mean = X_class.mean(axis=0)
        std = X_class.std(axis=0) + 1e-6  # Thêm 1e-6 để tránh chia cho 0
        prior_prob = np.mean(y_train == cls)

        model[cls] = {
            'mean': mean,
            'std': std,
            'prior_prob': prior_prob
        }
    return model


def predict_gaussian_nb(model, X_new):
    """ Dự đoán lớp cho một mẫu mới dựa trên mô hình đã huấn luyện """
    class_probabilities = {}

    for cls, params in model.items():
        mean = params['mean']
        std = params['std']
        prior_prob = params['prior_prob']

        # Tính tích xác suất cho từng đặc trưng
        feature_probs = [
            gaussian_pdf(X_new[i], mean[i], std[i]) for i in range(len(X_new))
        ]

        # Tổng xác suất là tích của các xác suất đặc trưng nhân với prior_prob
        total_prob = prior_prob * np.prod(feature_probs)
        class_probabilities[cls] = total_prob

    # Trả về lớp có xác suất cao nhất
    return max(class_probabilities, key=class_probabilities.get)


model = train_gaussian_nb(X_train, y_train)
y_pred_custom = [predict_gaussian_nb(model, X_test.iloc[i].values) for i in range(len(X_test))]
accuracy_custom = accuracy_score(y_test, y_pred_custom)
print(f'Custom GaussianNB Accuracy: {accuracy_custom}')

<ipython-input-11-ebd1e05df184>:46: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  gaussian_pdf(X_new[i], mean[i], std[i]) for i in range(len(X_new))

Custom GaussianNB Accuracy: 0.8086805200122837

In [ ]:
predictions_df_custom = X_test.copy()
predictions_df_custom['Actual Income'] = y_test.values
predictions_df_custom['Predicted Income'] = y_pred

#extract the output file
predictions_df_custom.to_csv("/content/drive/MyDrive/Census_dataset/predicted_income_custom.csv", index=False)